x-announceman: &announceman
  build: .
  volumes:
    - ./announceman_data:/src/announceman_data

services:
  announceman:
    <<: *announceman
    image: announceman:live
    restart: unless-stopped
    env_file: .env

  test:
    <<: *announceman
    image: announceman:test
    restart: "no"
    profiles: [test]
    env_file:
      - path: .env.test
        required: false
